# 1. `kubectl create -f section-1-6-pod-definition.yaml`
# 2. `kubectl get pod`
# 3. `kubectl describe pod  myapp-pod`
# 4. ``kubectl delete -f section-1-6-pod-definition.yaml``
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
