version: "3"

services:

  db:
    image: mariadb
    environment:
      # MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 213123
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    healthcheck:
      test: bash -c 'mysqladmin ping -p"$$MYSQL_ROOT_PASSWORD"'
      interval: 5s
      retries: 5
      timeout: 3s
      start_period: 10s
    restart: always
  
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
    
    depends_on:
      db:
        condition: service_healthy


  